import './gulp/tasks/build';
import './gulp/tasks/clean';
import './gulp/tasks/development';
import './gulp/tasks/fonts';
import './gulp/tasks/scripts';
import './gulp/tasks/server';
import './gulp/tasks/styles';
import './gulp/tasks/views';
import './gulp/tasks/watch';
